apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: example-1
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  type: LoadBalancer
  ports:
  - port: 50051
    name: tcp
  selector:
    app: example-1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: example-1
    spec:
      containers:
      - name: backend
        image: bazel/backend:backend
        env:
        resources:
          requests:
            memory: "1Mi"
            cpu: "10m"
        ports:
        - containerPort: 9090
        - containerPort: 50051
        #volumeMounts:
        #- name: secrets
        #  mountPath: /etc/secrets
        #  readOnly: true
      #volumes:
      #- name: secrets
      #  secret:
      #    secretName: frontend-secrets
