apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: horlick.me
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: ssl
  - port: 80
    name: tcp
  selector:
    name: horlick.me
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: horlick.me
    spec:
      containers:
      - name: frontend
        image: eu.gcr.io/quant-finance-1143/horlick.me:latest
        env:
        resources:
          requests:
            memory: "1Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: frontend-secrets
