apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
  #annotations:
  #  prometheus.io/scrape: 'true'
  #  prometheus.io/port: '9090'
spec:
  type: NodePort
  ports:
  - port: 9090
    name: tcp
  selector:
    app: prometheus
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: bazel/backend:prometheus
        env:
        resources:
          requests:
            memory: "300Mi"
            cpu: "100m"
        ports:
        - containerPort: 9090
